version: "3.9"

volumes:
  db_data:

services:
  db:
    image: "postgres:14.2"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - "stack.env"
    environment:
      PGUSER: "postgres"
      PGPASSWORD: "password"
      PGDATABASE: "impressive_strawberry"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "impressive_strawberry"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    deploy:
      resources:
        limits:
          memory: "64M"

  impressive:
    image: "ghcr.io/ryghub/impressive-strawberry:latest"
    restart: unless-stopped
    ports:
      - "127.0.0.1:30074:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      IS_DB_URI: "postgresql://postgres:password@db/impressive_strawberry"
      CORS_ALLOW_ORIGINS: "https://strawberry.ryg.one"
