version: "3.9"

volumes:
  db-data:

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: impressive_strawberry

  impressive:
    image: ghcr.io/ryghub/impressive-strawberry
    restart: always
    ports:
      - "30074:80"
    depends_on:
      - db
    environment:
      IS_DB_URI: postgresql://postgres:password@db/impressive_strawberry
      IS_WEB_PORT: 80
      IS_SECRET: "CHANGE-ME"
      CORS_ALLOW_ORIGINS: "https://strawberry.ryg.one"
