version: "3.9"

volumes:
  db-data:

services:
  db:
    image: "postgres"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: impressive_strawberry

  impressive:
    build: "."
    restart: unless-stopped
    ports:
      - target: 80
        published: 30074
        protocol: tcp
        mode: host
    depends_on:
      - db
    environment:
      IS_DB_URI: postgresql://postgres:password@db/impressive_strawberry
      IS_SECRET: "CHANGE-ME"
      CORS_ALLOW_ORIGINS: "https://strawberry.ryg.one"
