version: "3.9"

volumes:
  db_data:

services:
  db:
    image: "postgres"
    restart: unless-stopped
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "impressive_strawberry"

  impressive:
    image: "ghcr.io/ryghub/impressive-strawberry:latest"
    restart: unless-stopped
    ports:
      - "127.0.0.1:30074:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      IS_DB_URI: "postgresql://postgres:password@db/impressive_strawberry"
      CORS_ALLOW_ORIGINS: "https://strawberry.ryg.one"
