name: "Release"

on:
  release:
    types:
      - published

jobs:
  analyze-codeql:
    name: "Perform CodeQL analysis"
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Initialize CodeQL"
        uses: github/codeql-action/init@v1
        with:
          languages: python

      - name: "Perform CodeQL analysis"
        uses: github/codeql-action/analyze@v1

  analyze-pytest:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2

      - name: "Setup Poetry"
        uses: abatilo/actions-poetry@v2.1.4

      - name: "Setup Poetry Python environment"
        id: pyenv
        uses: Steffo99/actions-poetry-deps@0.2.3

      - name: "Run tests"
        run: |
          source ${{ steps.pyenv.outputs.pyenv }}/activate
          pytest --verbose --cov=. --cov-report=html

      - name: "Upload coverage"
        uses: actions/upload-artifact@v2
        with:
          name: "code-coverage-report"
          path: htmlcov

  build-package:
    name: "Build Python package"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2

      - name: "Setup Poetry"
        uses: abatilo/actions-poetry@v2.1.4

      - name: "Setup Poetry Python environment"
        uses: Steffo99/actions-poetry-deps@0.2.3

      - name: "Build Poetry package"
        run: poetry build --no-interaction

      - name: "Upload package artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "package.tar.gz"
          path: dist/*.tar.gz

      - name: "Upload wheel artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "package.whl"
          path: dist/*-py3-none-any.whl

  build-docs:
    name: "Build documentation"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2

      - name: "Setup Poetry"
        uses: abatilo/actions-poetry@v2.1.4

      - name: "Setup Poetry Python environment"
        id: "pyenv"
        uses: Steffo99/actions-poetry-deps@0.2.3

      - name: "Build HTML documentation with Sphinx"
        working-directory: docs/
        run: |
          source ${{ steps.pyenv.outputs.pyenv }}/activate
          make html

      - name: "Upload docs artifact"
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "documentation"
          path: "docs/build/html/"

  # publish-package:
  #   name: "Publish Python package"
  #   runs-on: ubuntu-latest
  #   needs:
  #     - analyze-pytest
  #     - analyze-codeql
  #     - build-package
  #     - build-docs
  #
  #   steps:
  #     ???

  publish-docs:
    name: "Publish documentation on GitHub Pages"
    runs-on: ubuntu-latest
    needs:
      - analyze-pytest
      - analyze-codeql
      - build-package
      - build-docs

    steps:
      - name: "Download docs artifact"
        uses: actions/download-artifact@v2.1.0
        with:
          name: "documentation"
          path: "docs/build/html/"

      - name: "Publish build to GitHub Pages"
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "docs/build/html/"
          enable_jekyll: false
