name: "Test code using Pytest"
on:
  push:
    branches: [ "main" ]
    paths:
      - "impressive_strawberry/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "impressive_strawberry/**"
jobs:
  testanalyze:
    name: "Test and analyze source"
    runs-on: "ubuntu-latest"

    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@main

      - name: "Setup Python"
        uses: actions/setup-python@main
        with:
          python-version: "3.10.1"

      - name: "Setup Poetry"
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11

      # - name: "Initialize CodeQL"
      #   uses: github/codeql-action/init@v1
      #   with:
      #     languages: "python"

      # - name: "Perform CodeQL Analysis"
      #   uses: github/codeql-action/analyze@v1

      - name: "Install backend dependencies"
        run: poetry install --no-interaction

      - name: "Find Poetry Python environment"
        run: echo "pythonLocation=$(poetry env list --full-path | cut -f1 -d' ')/bin" >> $GITHUB_ENV

      - name: "Run tests"
        run: |
          source $pythonLocation/activate
          pytest --verbose --cov=. --cov-report=html

      - name: "Upload coverage"
        uses: actions/upload-artifact@v2
        with:
          name: "code-coverage-report"
          path: htmlcov

      - name: "Build package"
        run: |
          source $pythonLocation/activate
          poetry build --no-interaction

      - name: "Upload code package"
        uses: actions/upload-artifact@v2
        with:
          path: dist/impressive_strawberry-*.tar.gz

      - name: "Upload wheel package"
        uses: actions/upload-artifact@v2
        with:
          path: dist/impressive_strawberry-*-py3-none-any.whl

      - name: "Publish to PyPI"
        run: echo "Not yet."
