name: "Test suite"

on:
  # Modification of a project file in the main branch
  push:
    branches:
      - main
    paths:
      - "impressive_strawberry/**"
      - "pyproject.toml"
      - "poetry.lock"
  # Pull request to the main branch modifying a project file
  pull_request:
    branches:
      - main
    paths:
      - "impressive_strawberry/**"
      - "pyproject.toml"
      - "poetry.lock"
  # Triggered by a new releaes
  workflow_call:

jobs:
  test:
    uses: Steffo99/.github/.github/workflows/test-poetry-pytest.yml@main

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"